insert into Course (sigle,title, etc) values ('MAT1', 'Mathematics', 6)
insert into Course (sigle,title, etc) values ('DEV1', 'Development', 6)
insert into Course (sigle,title, etc) values ('ENG1', 'English', 6)
insert into Course (sigle,title, etc) values ('SCI1', 'Science', 10)
insert into Course (sigle,title, etc) values ('HIS1', 'History', 6)
insert into Course (sigle,title, etc) values ('PHY1', 'Physics', 6)
insert into Course (sigle,title, etc) values ('CHE1', 'Chemistry', 3)
insert into Course (sigle,title, etc) values ('BIO1', 'Biology', 1)
insert into Course (sigle,title, etc) values ('CS1', 'Computer Science', 2)
insert into Course (sigle,title, etc) values ('ART1', 'Art', 6)
insert into Student (id,name,gender,section ) values (1, 'Mohamed', 0, 1)
insert into Student (id,name,gender,section ) values (2, 'Dracaufeu', 1 , 2)
insert into Student (id,name,gender,section ) values (3, 'Rattata', 1, 0)
insert into Student (id,name,gender,section ) values (4, 'Aurelien', 1, 2)
insert into Student (id,name,gender,section ) values (5, 'Martine', 1, 1)
insert into Student (id,name,gender,section ) values (6, 'Kun', 0, 2)